### PR TITLE
Build with GCC 8.2.1

### PR DESCRIPTION
**Pull request by plusk01**
Build with `gcc-arm-none-eabi-8-2018-q4-major` toolchain.

### CODE REVIEW

**Comment by plusk01** [comment]
Needs https://github.com/rosflight/airbourne_f4/pull/42 to be merged, then airbourne submodule needs to be updated to point to master.

**Comment by plusk01** [comment]
Should update https://docs.rosflight.org/developer-guide/building-flashing/ before merging

**Comment by dpkoch** [comment]
Looks good, thanks. What's the reason for increasing the parameter name length to 18? The potential issue with that is the mavlink message only supports 16 characters

**Comment by plusk01** [comment]
Ah I see.

I was trying to avoid errors like the following, using `memcpy` with GCC 8.2.1:
```bash
In member function 'void rosflight_firmware::Params::init_param_int(uint16_t, const char*, int32_t)',
    inlined from 'void rosflight_firmware::Params::set_defaults()' at ../../src/param.cpp:102:17:
../../src/param.cpp:58:9: error: 'void* memcpy(void*, const void*, size_t)' forming offset [11, 16] is out of the bounds [0, 10] [-Werror=array-bounds]
   memcpy(params.names[id], name, PARAMS_NAME_LENGTH);
   ~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In member function 'void rosflight_firmware::Params::init_param_int(uint16_t, const char*, int32_t)',
    inlined from 'void rosflight_firmware::Params::set_defaults()' at ../../src/param.cpp:103:17:
../../src/param.cpp:58:9: error: 'void* memcpy(void*, const void*, size_t)' forming offset [15, 16] is out of the bounds [0, 14] [-Werror=array-bounds]
   memcpy(params.names[id], name, PARAMS_NAME_LENGTH);
   ~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
...
```

Switching to `strncpy` gives these errors, since with 16 len `"PID_PITCH_RATE_P"` gets truncated (16 + null).
```bash
In member function 'void rosflight_firmware::Params::init_param_int(uint16_t, const char*, int32_t)',
    inlined from 'void rosflight_firmware::Params::set_defaults()' at ../../src/param.cpp:261:17:
../../src/param.cpp:57:10: error: 'char* strncpy(char*, const char*, size_t)' output truncated before terminating nul copying 16 bytes from a string of the same length [-Werror=stringop-truncation]
   strncpy(params.names[id], name, PARAMS_NAME_LENGTH);
   ~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In member function 'void rosflight_firmware::Params::init_param_float(uint16_t, const char*, float)',
    inlined from 'void rosflight_firmware::Params::set_defaults()' at ../../src/param.cpp:235:19:
../../src/param.cpp:64:10: error: 'char* strncpy(char*, const char*, size_t)' output truncated before terminating nul copying 16 bytes from a string of the same length [-Werror=stringop-truncation]
   strncpy(params.names[id], name, PARAMS_NAME_LENGTH);
   ~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
...
```

I guess a better solution with pedantic warnings is to use `strlen`:

```c++
const uint8_t len = (strlen(name)>PARAMS_NAME_LENGTH) ? PARAMS_NAME_LENGTH : strlen(name);
memcpy(params.names[id], name, len);
```

**Comment by superjax** [comment]
This is a lot better than my attempts to fix this.  Thanks.
